# Generated by Django 4.2.27 on 2025-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
