# Generated by Django 4.2.27 on 2025-12-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_clinica_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('profissional', 'data', 'horario')},
        ),
    ]
