# Generated by Django 4.2.27 on 2025-12-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        ('agendamentos', '0008_prontuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.plano'),
        ),
    ]
