# Generated by Django 4.2.27 on 2025-12-18 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_clinica_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='whatsapp_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WhatsappLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('confirmacao', 'Confirmação'), ('lembrete', 'Lembrete'), ('cancelamento', 'Cancelamento')], max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='agendamentos.clinica')),
            ],
        ),
    ]
