# Generated by Django 4.2.27 on 2026-01-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_clinica_whatsapp_extra_whatsapplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='agendamentos.servico'),
        ),
    ]
