# Generated by Django 4.2.27 on 2026-01-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_profissional_servicos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinica',
            options={'permissions': [('ver_dashboard', 'Pode ver o dashboard'), ('gerenciar_agendamentos', 'Pode gerenciar agendamentos'), ('gerenciar_servicos', 'Pode gerenciar serviços'), ('gerenciar_profissionais', 'Pode gerenciar profissionais'), ('ver_relatorios', 'Pode ver relatórios')]},
        ),
    ]
