# Generated by Django 4.2.27 on 2026-02-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_usuarioclinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'ordering': ['-data'], 'verbose_name': 'Prontuário', 'verbose_name_plural': 'Prontuários'},
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='anotacoes',
            field=models.TextField(verbose_name='Anotações clínicas'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='agendamentos.clinica'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='agendamentos.paciente'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_realizados', to='agendamentos.profissional'),
        ),
    ]
