# Generated by Django 4.2.27 on 2026-02-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_alter_prontuario_options_alter_prontuario_anotacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='prontuario',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='agendamentos.agendamento'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='anotacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.clinica'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.paciente'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.profissional'),
        ),
    ]
