# Generated by Django 4.2.27 on 2026-02-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0015_alter_prontuario_options_prontuario_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='codigo_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='codigo_login',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tentativas_codigo',
            field=models.IntegerField(default=0),
        ),
    ]
