# Generated by Django 4.2.27 on 2026-03-21 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0016_paciente_codigo_expira_em_paciente_codigo_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('etapa', models.CharField(default='inicio', max_length=50)),
                ('data', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.profissional')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.servico')),
            ],
        ),
    ]
