# Generated by Django 4.2.27 on 2026-03-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0017_conversawhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='whatsapp_instance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
