# Generated by Django 4.2.27 on 2026-03-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0018_clinica_whatsapp_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='whatsapp_status',
            field=models.CharField(default='desconectado', max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='whatsapp_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
