# Generated by Django 4.2.27 on 2026-03-27 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamentos', '0019_clinica_whatsapp_status_clinica_whatsapp_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='whatsapp_extra',
            new_name='limite_mensagens',
        ),
        migrations.AddField(
            model_name='clinica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinica',
            name='user',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
