# Generated by Django 4.2.27 on 2026-03-30 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamentos', '0020_rename_whatsapp_extra_clinica_limite_mensagens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinica', to=settings.AUTH_USER_MODEL),
        ),
    ]
