# Generated by Django 4.2.27 on 2026-04-08 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_remove_plano_max_servicos_plano_tem_relatorios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamentos', '0021_alter_clinica_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinica.plano'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinica',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
