# Generated by Django 4.2.27 on 2026-04-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0022_alter_clinica_plano_alter_clinica_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinica',
            options={'permissions': [('ver_dashboard', 'Pode ver o dashboard'), ('gerenciar_agendamentos', 'Pode gerenciar agendamentos'), ('gerenciar_servicos', 'Pode gerenciar serviços'), ('gerenciar_profissionais', 'Pode gerenciar profissionais'), ('ver_relatorios', 'Pode ver relatórios'), ('gerenciar_prontuario', 'Pode gerenciar prontuario'), ('gerenciar_usuarios', 'Pode gerenciar usuarios')]},
        ),
    ]
