# Generated by Django 4.2.27 on 2026-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0024_alter_clinica_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='bloqueios',
            field=models.IntegerField(default=0),
        ),
    ]
