# Generated by Django 4.2.27 on 2026-04-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0025_paciente_bloqueado_ate_paciente_bloqueios'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='data_fim_plano',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='data_inicio_plano',
            field=models.DateField(blank=True, null=True),
        ),
    ]
