# Generated by Django 4.2.27 on 2026-04-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0026_clinica_data_fim_plano_clinica_data_inicio_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('faltou', 'Faltou')], default='pendente', max_length=20),
        ),
    ]
