# Generated by Django 4.2.27 on 2026-04-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0027_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversawhatsapp',
            name='clinica',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='agendamentos.clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='agendamentos.clinica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversawhatsapp',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='conversawhatsapp',
            unique_together={('clinica', 'telefone')},
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('clinica', 'telefone')},
        ),
    ]
