# Generated by Django 4.2.27 on 2026-06-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0028_conversawhatsapp_clinica_paciente_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
