# Generated by Django 4.2.27 on 2025-12-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='max_agendamentos_mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='max_profissionais',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='max_servicos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='max_whatsapp_mes',
            field=models.IntegerField(blank=True, help_text='Quantidade de mensagens WhatsApp incluídas no plano (null = ilimitado)', null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='pode_ver_paciente',
            field=models.BooleanField(default=True),
        ),
    ]
