# Generated by Django 4.2.27 on 2026-04-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_plano_max_agendamentos_mes_plano_max_profissionais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='max_servicos',
        ),
        migrations.AddField(
            model_name='plano',
            name='tem_relatorios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_whatsapp_mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
