# Generated by Django 4.2.27 on 2026-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_remove_plano_max_servicos_plano_tem_relatorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='max_servicos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
