# Generated by Django 4.2.27 on 2026-05-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0028_conversawhatsapp_clinica_paciente_clinica_and_more'),
        ('clinica', '0004_plano_max_servicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('codigo_pix', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.clinica')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.plano')),
            ],
        ),
    ]
